name: OpenSSF Scorecard

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read
  security-events: write
  id-token: write

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Scorecard
        uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          publish_results: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          results_format: sarif
          checks_to_run: >-
            Binary-Artifacts,Branch-Protection,CI-Tests,CII-Best-Practices,
            Code-Review,Contributors,Dangerous-Workflow,Dependency-Update-Tool,
            Fuzzing,License,Maintained,Packaging,Pinned-Dependencies,SAST,
            SBOM,Security-Policy,Signed-Releases,Token-Permissions,
            Vulnerabilities,Webhooks

      - name: Upload results to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
